# Generated by Django 5.0.1 on 2024-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
