# Generated by Django 5.0.1 on 2024-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
