# Generated by Django 5.0.1 on 2024-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_actor_award_director_moviecharacter_studio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='MovieCharacter',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
